<?php
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * WP Survey AI Report Generator
 *
 * Each section is generated by a SEPARATE PHP/AJAX call so no single
 * HTTP request runs longer than ~40 seconds — no timeouts.
 *
 * Sections (called one at a time from JS):
 *   overview → questions → cross → conclusions
 */
class WP_Survey_AI_Report {

    const OR_URL = 'https://openrouter.ai/api/v1/chat/completions';

    private static function key_report( int $id )  { return 'wps_ai_report_'  . $id; }
    private static function key_status( int $id )  { return 'wps_ai_status_'  . $id; }

    // ── Public read API ───────────────────────────────────────────────────────

    public static function get_report( int $id )  { return get_option( self::key_report( $id ) )  ?: null; }
    public static function get_status( int $id )  { return get_option( self::key_status( $id ) )  ?: 'idle'; }

    public static function delete_report( int $id ): void {
        delete_option( self::key_report( $id ) );
        delete_option( self::key_status( $id ) );
    }

    // ── Section runner ────────────────────────────────────────────────────────
    // Called once per AJAX request. $section: overview|questions|cross|conclusions

    public static function run_section( int $survey_id, string $section ): array {
        $api_key = get_option( 'wps_ai_api_key', '' );
        if ( empty( $api_key ) ) {
            return [ 'success' => false, 'error' => 'OpenRouter API key not set.' ];
        }

        $survey = WP_Survey_Database::get_survey( $survey_id );
        if ( ! $survey ) {
            return [ 'success' => false, 'error' => 'Survey not found.' ];
        }

        update_option( self::key_status( $survey_id ), 'running' );

        // Load partial report accumulated so far
        $report = get_option( self::key_report( $survey_id ) ) ?: [];

        $data     = self::build_survey_data( $survey_id, $survey );
        $language = get_option( 'wps_ai_language', 'English' );
        $persona  = get_option( 'wps_ai_custom_prompt', '' ) ?:
            "You are an expert political analyst and survey researcher with deep knowledge of " .
            "Cypriot society, politics, and public opinion. Analyze data rigorously and produce " .
            "thorough, data-driven insights suitable for official publication. Never fabricate data.";
        $model    = get_option( 'wps_ai_model', 'anthropic/claude-3.5-sonnet' );
        $system   = "Respond entirely in {$language}. {$persona}\n\n" .
                    "Return ONLY a valid JSON object starting with { — no markdown, no explanation outside JSON.";

        switch ( $section ) {

            case 'overview':
                $r = self::call( $api_key, $model, $system, self::p_overview( $data ) );
                if ( ! $r['success'] ) { update_option( self::key_status( $survey_id ), 'error' ); return [ 'success' => false, 'error' => $r['error'] ]; }
                $report['overview'] = $r['data'];
                update_option( self::key_report( $survey_id ), $report );
                return [ 'success' => true, 'done' => false ];

            case 'questions':
                // Split into batches of 5 to avoid token limit truncation
                $all_questions = [];
                if ( $survey->survey_type === 'multi-question' ) {
                    $q_list = WP_Survey_Database::get_questions( $survey_id );
                } else {
                    // Treat simple survey as one "question"
                    $q_list = [ (object)[ 'id' => 0, 'question_text' => $survey->question ] ];
                }

                $batch_size = 5;
                $batches    = array_chunk( $q_list, $batch_size );

                foreach ( $batches as $bi => $batch ) {
                    $batch_data = self::build_batch_data( $survey_id, $survey, $batch, count( $batches ), $bi + 1 );
                    $r = self::call( $api_key, $model, $system, self::p_questions_batch( $batch_data, $bi + 1, count( $batches ) ) );
                    if ( ! $r['success'] ) {
                        update_option( self::key_status( $survey_id ), 'error' );
                        return [ 'success' => false, 'error' => "Questions batch " . ( $bi + 1 ) . ": " . $r['error'] ];
                    }
                    if ( ! empty( $r['data']['questions'] ) ) {
                        $all_questions = array_merge( $all_questions, $r['data']['questions'] );
                    }
                }

                $report['questions'] = [ 'questions' => $all_questions ];
                update_option( self::key_report( $survey_id ), $report );
                return [ 'success' => true, 'done' => false ];

            case 'cross':
                if ( $survey->survey_type === 'multi-question' ) {
                    $r = self::call( $api_key, $model, $system, self::p_cross( $data ) );
                    if ( ! $r['success'] ) { update_option( self::key_status( $survey_id ), 'error' ); return [ 'success' => false, 'error' => $r['error'] ]; }
                    $report['cross'] = $r['data'];
                } else {
                    $report['cross'] = null; // skipped for simple surveys
                }
                update_option( self::key_report( $survey_id ), $report );
                return [ 'success' => true, 'done' => false ];

            case 'conclusions':
                $r = self::call( $api_key, $model, $system, self::p_conclusions( $data, $report ) );
                if ( ! $r['success'] ) { update_option( self::key_status( $survey_id ), 'error' ); return [ 'success' => false, 'error' => $r['error'] ]; }
                $report['conclusions'] = $r['data'];

                // Stamp metadata and mark complete
                global $wpdb;
                $report['_meta'] = [
                    'generated_at' => current_time( 'mysql' ),
                    'model'        => $model,
                    'language'     => $language,
                    'survey_title' => $survey->title,
                    'survey_id'    => $survey_id,
                    'total_votes'  => (int) $wpdb->get_var( $wpdb->prepare(
                        "SELECT COUNT(*) FROM {$wpdb->prefix}survey_responses WHERE survey_id = %d", $survey_id
                    ) ),
                ];
                update_option( self::key_report( $survey_id ), $report );
                update_option( self::key_status( $survey_id ), 'done' );
                return [ 'success' => true, 'done' => true, 'report' => $report ];

            default:
                return [ 'success' => false, 'error' => "Unknown section: {$section}" ];
        }
    }

    // ── Prompt builders ───────────────────────────────────────────────────────

    private static function p_questions_batch( string $d, int $batch_num, int $total_batches ): string {
        $context = $total_batches > 1
            ? "This is batch {$batch_num} of {$total_batches}. Analyze ONLY the questions listed below."
            : "Analyze the question below.";
        return "Analyze each question in this batch. {$context}\n\n" .
               "Return a JSON object:\n" .
               "{\n  \"questions\": [\n    {\n" .
               "      \"question\": \"exact question text\",\n" .
               "      \"leading_choice\": \"winner name\",\n" .
               "      \"leading_pct\": \"e.g. 80.3%\",\n" .
               "      \"runner_up\": \"2nd place name and percentage\",\n" .
               "      \"analysis\": \"2-3 paragraphs: what this result means, why voters lean this way, what it reveals about public opinion\",\n" .
               "      \"notable\": \"1 sentence on the most surprising or significant aspect\"\n" .
               "    }\n  ]\n}\n\n" .
               "IMPORTANT: Include one entry for every question listed. Keep each analysis concise — 2 paragraphs max.\n\n" .
               "Data:\n{$d}\n\nJSON only:";
    }

    private static function build_batch_data( int $survey_id, $survey, array $q_list, int $total_batches, int $batch_num ): string {
        global $wpdb;
        $rt    = $wpdb->prefix . 'survey_responses';
        $total = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM $rt WHERE survey_id=%d", $survey_id ) );

        $lines = [
            "SURVEY: {$survey->title}",
            "Total responses: {$total}",
            $total_batches > 1 ? "Batch {$batch_num}/{$total_batches}" : "",
            "",
            "QUESTIONS TO ANALYZE:",
        ];

        if ( $survey->survey_type === 'multi-question' ) {
            // Figure out the offset so question numbers are correct
            $all_q   = WP_Survey_Database::get_questions( $survey_id );
            $q_index = 0;
            $offset  = ( $batch_num - 1 ) * 5; // batch_size = 5

            foreach ( $q_list as $q ) {
                $global_idx = $offset + $q_index + 1;
                $qt = (int) $wpdb->get_var( $wpdb->prepare(
                    "SELECT COUNT(*) FROM $rt WHERE survey_id=%d AND question_id=%d", $survey_id, $q->id
                ) );
                $lines[] = "";
                $lines[] = "Q{$global_idx}: {$q->question_text} ({$qt} answers)";
                foreach ( WP_Survey_Database::get_choices( $survey_id, $q->id ) as $c ) {
                    $v   = (int) $wpdb->get_var( $wpdb->prepare(
                        "SELECT COUNT(*) FROM $rt WHERE survey_id=%d AND question_id=%d AND choice_id=%d",
                        $survey_id, $q->id, $c->id
                    ) );
                    $pct = $qt > 0 ? round( $v / $qt * 100, 1 ) : 0;
                    $lines[] = "  • {$c->title}: {$v} votes ({$pct}%)";
                }
                $q_index++;
            }
        } else {
            $lines[] = "";
            $lines[] = "Question: {$survey->question} ({$total} answers)";
            foreach ( WP_Survey_Database::get_choices( $survey_id ) as $c ) {
                $v   = (int) $wpdb->get_var( $wpdb->prepare(
                    "SELECT COUNT(*) FROM $rt WHERE survey_id=%d AND choice_id=%d", $survey_id, $c->id
                ) );
                $pct = $total > 0 ? round( $v / $total * 100, 1 ) : 0;
                $lines[] = "  • {$c->title}: {$v} votes ({$pct}%)";
            }
        }

        return implode( "\n", array_filter( $lines, fn($l) => $l !== null ) );
    }

    private static function p_overview( string $d ): string {
        return "Analyze this survey and return a JSON object:\n\n" .
               "{\n" .
               "  \"executive_summary\": \"3-4 paragraphs covering the survey topic, participation, and headline findings with specific percentages\",\n" .
               "  \"participation_note\": \"1 sentence about sample size and what it represents\",\n" .
               "  \"key_findings\": [\"finding with specific number 1\", \"finding 2\", \"finding 3\", \"finding 4\", \"finding 5\"]\n" .
               "}\n\nSurvey:\n{$d}\n\nJSON only:";
    }

    private static function p_questions( string $d ): string {
        return "Analyze every single question in this survey. Include ALL of them — no skipping.\n\n" .
               "Return a JSON object:\n" .
               "{\n  \"questions\": [\n    {\n" .
               "      \"question\": \"exact question text\",\n" .
               "      \"leading_choice\": \"winner name\",\n" .
               "      \"leading_pct\": \"e.g. 80.3%\",\n" .
               "      \"runner_up\": \"2nd place name and percentage\",\n" .
               "      \"analysis\": \"2-3 paragraphs: what the result means, why voters lean this way, what it reveals about public opinion\",\n" .
               "      \"notable\": \"1 sentence on the most surprising or significant aspect\"\n" .
               "    }\n  ]\n}\n\n" .
               "The questions array MUST have one entry for EVERY question listed below.\n\n" .
               "Survey:\n{$d}\n\nJSON only:";
    }

    private static function p_cross( string $d ): string {
        return "Analyze all questions together to find cross-question patterns.\n\n" .
               "Return a JSON object:\n{\n" .
               "  \"patterns\": \"2-3 paragraphs on how opinions cluster across questions\",\n" .
               "  \"voter_segments\": \"2 paragraphs on distinct voter profiles that emerge\",\n" .
               "  \"correlations\": [\"specific correlation 1\", \"correlation 2\", \"correlation 3\"],\n" .
               "  \"overall_mood\": \"1 paragraph on the dominant public mood across the whole survey\"\n" .
               "}\n\nSurvey:\n{$d}\n\nJSON only:";
    }

    private static function p_conclusions( string $d, array $prev ): string {
        $p = json_encode( $prev, JSON_UNESCAPED_UNICODE );
        return "Write the final conclusions based on the survey data and prior analysis.\n\n" .
               "Return a JSON object:\n{\n" .
               "  \"main_conclusion\": \"2-3 paragraphs on what this survey tells us about Cypriot public opinion\",\n" .
               "  \"political_implications\": \"1-2 paragraphs on implications for politicians and decision-makers\",\n" .
               "  \"media_headlines\": [\"headline option 1\", \"headline option 2\", \"headline option 3\"],\n" .
               "  \"recommendations\": [\"actionable recommendation 1\", \"recommendation 2\", \"recommendation 3\"]\n" .
               "}\n\nSurvey:\n{$d}\n\nPrior analysis:\n{$p}\n\nJSON only:";
    }

    // ── Survey data string ────────────────────────────────────────────────────

    private static function build_survey_data( int $survey_id, $survey ): string {
        global $wpdb;
        $rt    = $wpdb->prefix . 'survey_responses';
        $total = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM $rt WHERE survey_id=%d", $survey_id ) );
        $first = $wpdb->get_var( $wpdb->prepare( "SELECT MIN(created_at) FROM $rt WHERE survey_id=%d", $survey_id ) );
        $last  = $wpdb->get_var( $wpdb->prepare( "SELECT MAX(created_at) FROM $rt WHERE survey_id=%d", $survey_id ) );

        $lines = [
            "SURVEY: {$survey->title}",
            $survey->description ? "Description: {$survey->description}" : null,
            "Total responses: {$total}",
            "Period: " . ( $first ? date( 'Y-m-d', strtotime( $first ) ) : 'N/A' ) .
                " – " . ( $last  ? date( 'Y-m-d', strtotime( $last  ) ) : 'N/A' ),
            "",
            "RESULTS:",
        ];
        $lines = array_filter( $lines, fn($l) => $l !== null );

        if ( $survey->survey_type === 'multi-question' ) {
            foreach ( WP_Survey_Database::get_questions( $survey_id ) as $qi => $q ) {
                $qt = (int) $wpdb->get_var( $wpdb->prepare(
                    "SELECT COUNT(*) FROM $rt WHERE survey_id=%d AND question_id=%d", $survey_id, $q->id
                ) );
                $lines[] = "";
                $lines[] = "Q" . ( $qi + 1 ) . ": {$q->question_text} ({$qt} total answers)";
                foreach ( WP_Survey_Database::get_choices( $survey_id, $q->id ) as $c ) {
                    $v   = (int) $wpdb->get_var( $wpdb->prepare(
                        "SELECT COUNT(*) FROM $rt WHERE survey_id=%d AND question_id=%d AND choice_id=%d",
                        $survey_id, $q->id, $c->id
                    ) );
                    $pct = $qt > 0 ? round( $v / $qt * 100, 1 ) : 0;
                    $lines[] = "  • {$c->title}: {$v} votes ({$pct}%)";
                }
            }
        } else {
            $lines[] = "";
            $lines[] = "Question: {$survey->question} ({$total} total answers)";
            foreach ( WP_Survey_Database::get_choices( $survey_id ) as $c ) {
                $v   = (int) $wpdb->get_var( $wpdb->prepare(
                    "SELECT COUNT(*) FROM $rt WHERE survey_id=%d AND choice_id=%d", $survey_id, $c->id
                ) );
                $pct = $total > 0 ? round( $v / $total * 100, 1 ) : 0;
                $lines[] = "  • {$c->title}: {$v} votes ({$pct}%)";
            }
        }

        return implode( "\n", $lines );
    }

    // ── OpenRouter API call ───────────────────────────────────────────────────

    private static function call( string $key, string $model, string $sys, string $user ): array {
        @set_time_limit( 120 );

        $res = wp_remote_post( self::OR_URL, [
            'timeout' => 90,
            'headers' => [
                'Authorization' => 'Bearer ' . $key,
                'Content-Type'  => 'application/json',
                'HTTP-Referer'  => get_site_url(),
                'X-Title'       => 'WP Survey Analysis',
            ],
            'body' => wp_json_encode( [
                'model'       => $model,
                'max_tokens'  => 4000,
                'temperature' => 0.3,
                'messages'    => [
                    [ 'role' => 'system', 'content' => $sys  ],
                    [ 'role' => 'user',   'content' => $user ],
                ],
            ] ),
        ] );

        if ( is_wp_error( $res ) ) return [ 'success' => false, 'error' => $res->get_error_message() ];

        $code = wp_remote_retrieve_response_code( $res );
        $json = json_decode( wp_remote_retrieve_body( $res ), true );

        if ( $code !== 200 ) {
            return [ 'success' => false, 'error' => $json['error']['message'] ?? "HTTP {$code}" ];
        }

        $txt = $json['choices'][0]['message']['content'] ?? '';
        $txt = preg_replace( '/^```(?:json)?\s*/m', '', $txt );
        $txt = preg_replace( '/```\s*$/m', '', $txt );
        $txt = trim( $txt );
        if ( ! str_starts_with( $txt, '{' ) && preg_match( '/\{[\s\S]*\}/s', $txt, $m ) ) $txt = $m[0];

        $data = json_decode( $txt, true );
        if ( json_last_error() !== JSON_ERROR_NONE ) {
            return [ 'success' => false, 'error' => 'AI returned invalid JSON. Raw: ' . substr( $txt, 0, 300 ) ];
        }
        return [ 'success' => true, 'data' => $data ];
    }
}